server:
  requestLog:
    appenders:
      - type: console
  applicationConnectors:
    - type: http
      port: 8085
  adminConnectors:
    - type: http
      port: 8086
  gzip:
    enabled: false

logging:
  appenders:
    - type: file
      threshold: INFO
      currentLogFilename: "boxed-api.log"
      archivedLogFilenamePattern: "boxed-api-%d-%i.log.gz"
      archivedFileCount: 3
      logFormat: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSX,UTC} %-5level msg=\"%msg\" uid=\"%X{correlationId}\" src=\"%logger{36}\" tid=\"[%thread]\"%n%ex{4}"
      maxFileSize: 1GB

database:
  driverClass: org.postgresql.Driver
  user: boxed
  password: boxed
  url: jdbc:postgresql://db:5432/boxed
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: SELECT 1
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: true
